-- PMS_REGULATORS_CONFIG
UPDATE PMS_REGULATORS_CONFIG SET REGULATOR_ADDRESS = 'this-gns' WHERE REGULATOR_ID = '1';
UPDATE PMS_REGULATORS_CONFIG SET REGULATOR_PORT = '8180' WHERE REGULATOR_ID = '1';

-- EBO_ADAPTER_CONFIGURATIONS
UPDATE EBO_ADAPTER_CONFIGURATIONS SET URL_SERVICE = 'http://this-gns:8180/B2CLottomaticaManagerService/B2CLottomaticaManagerService' WHERE PARTNER_ID = '1' AND BRAND_ID = '1' AND OPERATION_TYPE = '1';
UPDATE EBO_ADAPTER_CONFIGURATIONS SET URL_SERVICE = 'http://this-gns:8180/FidelityContext/fp-engine' WHERE PARTNER_ID = '1' AND BRAND_ID = '1' AND OPERATION_TYPE = '2';
UPDATE EBO_ADAPTER_CONFIGURATIONS SET URL_SERVICE = 'http://this-gns:8180/BOManagerPFFService/BOManagerPFFService' WHERE PARTNER_ID = '1' AND BRAND_ID = '1' AND OPERATION_TYPE = '4';

-- EBO_PFF_ADAPTER_CONFIGURATIONS
UPDATE EBO_PFF_ADAPTER_CONFIGURATIONS SET URL_SERVICE = 'http://this-gns:8180/BOManagerPFFService/BOManagerPFFService' WHERE PARTNER_ID = '1' AND BRAND_ID = '1' AND OPERATION_TYPE = '4';